# ==================================
# Configuracion para Circuit Breaker 
# ==================================

resilience4j.circuitbreaker:
    instances:
# Registramos el nombre que daremos al Circuit Breaker
# Si tuvieramos mas microservicios a los que llamaramos desde este
# se incluirian nuevas lineas con ese mismo formato   
# esta info esta copiada de https://resilience4j.readme.io/docs/getting-started-3      
        productCB:
            registerHealthIndicator: true
            slidingWindowSize: 10
            permittedNumberOfCallsInHalfOpenState: 3
            slidingWindowType: TIME_BASED
            minimumNumberOfCalls: 4
            waitDurationInOpenState: 5s
            failureRateThreshold: 50
            eventConsumerBufferSize: 10
